### ISSUE TITLE
The order of the reported tests should always be the same

### ISSUE THREAD

**Issue by jumaffre** [jumaffre/cimetrics#35]
As it stands, the order of the tests on the reported diagrams may differ between two runs, which makes it hard to compare the results between runs. Instead, the tests should always be ordered by name/label.

**Comment by achamayou** [comment]
I've wondered about that. A stable order seems good, but sorting by amount of change could make sense, since we're showing changes. On projects with a lot of metrics, you might even imagine a threshold config option that'd say "only show changes >5%".

If a value hasn't changed at all, you quite probably don't want to see it.

**Comment by jumaffre** [comment]
Good point. What about adding a parameter for this in `metrics.yml`? Stable order is default. Other options are ascending and descending as well as threshold with a value.

**Comment by achamayou** [comment]
Parameter is fine, but as always, the most important thing is a sensible default. I'm not sure what the sensible default is here (I'm leaning towards descending by amplitude of change).

**Comment by achamayou** [comment]
Trend view has a stable order by label, like default, and I don't see any point adding another ordering now that we're going with a grid.
