### ISSUE TITLE
Display branch history

### ISSUE THREAD

**Issue by jumaffre** [jumaffre/cimetrics#60]
Following https://github.com/jumaffre/cimetrics/issues/54, we should also display the evolution of the branch metrics (orange) against the target build (blue). That way, the evolution of the branch metrics against the target can be observed from a single comment.

**Comment by achamayou** [comment]
There's a few challenges with this:

1. Indicate that the branch points are raw data. One solution that was proposed is to display bars (like we do now for the last value, but perhaps without the marker for all but the last value)
2. Horizontal space, we probably want to cap to span or maybe span/2
3. Historical values for branch with the same name. We should probably use PR number for that, on top rather than instead of branch name to try and preserve the ability to run locally.

From a code perspective, this ought to be fairly easy, because the logic already exists for the target branch (it feeds into the ewma). If we take the opportunity to remove the old view too, we can probably implement this change with a large net deletion of code.
