### ISSUE TITLE
Group metrics by label

### ISSUE THREAD

**Issue by jumaffre** [jumaffre/cimetrics#75]
It should be possible to specify a label (optional) for each metric so that groups of metrics are plotted separately on the PR comment.

**Comment by letmaik** [comment]
What does label mean? From your description it sounds like multiple metrics can share the same label. If that's the case I find it confusing. Why not "group"?

**Comment by achamayou** [comment]
Group sounds more accurate, you are right.

**Comment by achamayou** [comment]
@letmaik I think the idea is to have either multiple pictures or maybe multiple sections of subplots that contain all the metrics in each group. “Micro-benchmarks”, “Distributed Tests on DC8”, that sort of thing. Same in monitoring issues.

**Comment by achamayou** [comment]
It looks like matplotlib now supports subfigures (https://matplotlib.org/devdocs/gallery/subplots_axes_and_figures/subfigures.html), so this might be a good way to go. It opens up a bunch of questions about layout, I think the simplest would be to have a vertical array of subfigures, each full-width, containing a matrix of subplots like now, but with a fixed number of horizontal elements to keep the plots the same size and aligned across labels.

I also wonder if "category" would be a better name than "label" because it less obviously implies the ability to have multiple values and sounds more hierarchical.

**Comment by achamayou** [comment]
Tried quickly swapping in sub-figures in #126, but it doesn't seem work at all with add_subplot(). Instead, examples pre-create static subplot matrices, and many of the calls are renamed (eg. `supxlabel()`) or perhaps not available.

**Comment by achamayou** [comment]
We will probably refine this, but there is now basic support for grouping metrics visually, which I think is good enough to use.
